# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hint',
            old_name='question',
            new_name='questionDiagnosis',
        ),
    ]
