# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_auto_20170903_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hint',
            old_name='questionDiagnosis',
            new_name='questiondiagnosis',
        ),
        migrations.RenameField(
            model_name='questiondiagnosis',
            old_name='questionDiagnosis_text',
            new_name='questiondiagnosis_text',
        ),
        migrations.RenameField(
            model_name='questiondiagnosis',
            old_name='questionDiagnosis_title',
            new_name='questiondiagnosis_title',
        ),
    ]
